import "./globals.css";
import Navigation from "../components/Navigation";
import Head from "next/head";
import Footer from "./(home-components)/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://use.typekit.net/mxc4zop.css" />
      </Head>
      <body className="bg-background">
        <Navigation />
        {children}
      </body>
      <Footer />
    </html>
  );
}
