import "./globals.css";
import Navigation from "../components/Navigation";
import Head from "next/head";
import Footer from "./(home-components)/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background">
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
